repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: ruff
        entry: ruff check
        name: ruff
        language: system
        types: [python]
    -   id: ruff-format
        entry: ruff format
        name: ruff-format
        language: system
        types: [python]
    -   id: isort
        entry: isort
        name: isort (python)
        language: system
        types: [python]
    -   id: black
        entry: black
        name: black
        language: system
        types: [python]
    -   id: flake8
        entry: flake8
        name: flake8
        language: system
        types: [file, python]
    -   id: mypy
        entry: mypy
        name: mypy
        language: system
        types: [python]
