repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
        # Run the linter.
    -   id: ruff
        # Run the formatter
    -   id: ruff-format
-   repo: local
    hooks:
    -   id: isort
        entry: isort
        name: isort (python)
        language: system
    -   id: black
        entry: black
        name: black
        language: system
        types: [python]
    -   id: flake8
        entry: flake8
        name: flake8
        language: system
        types: [file, python]
    -   id: mypy
        entry: mypy
        name: mypy
        language: system
        types: [python]
